server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  jpa:
    show-sql: true
  mail:
    host: maildev
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000